/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSpecialNeedsRouteImport } from './routes/services.special-needs'
import { Route as ServicesSeniorCommunitiesRouteImport } from './routes/services.senior-communities'
import { Route as ServicesPrivateCoachingRouteImport } from './routes/services.private-coaching'

const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSpecialNeedsRoute = ServicesSpecialNeedsRouteImport.update({
  id: '/special-needs',
  path: '/special-needs',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeniorCommunitiesRoute =
  ServicesSeniorCommunitiesRouteImport.update({
    id: '/senior-communities',
    path: '/senior-communities',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPrivateCoachingRoute = ServicesPrivateCoachingRouteImport.update({
  id: '/private-coaching',
  path: '/private-coaching',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/services': typeof ServicesRouteWithChildren
  '/work-with-us': typeof WorkWithUsRoute
  '/services/private-coaching': typeof ServicesPrivateCoachingRoute
  '/services/senior-communities': typeof ServicesSeniorCommunitiesRoute
  '/services/special-needs': typeof ServicesSpecialNeedsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/services/private-coaching': typeof ServicesPrivateCoachingRoute
  '/services/senior-communities': typeof ServicesSeniorCommunitiesRoute
  '/services/special-needs': typeof ServicesSpecialNeedsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/services': typeof ServicesRouteWithChildren
  '/work-with-us': typeof WorkWithUsRoute
  '/services/private-coaching': typeof ServicesPrivateCoachingRoute
  '/services/senior-communities': typeof ServicesSeniorCommunitiesRoute
  '/services/special-needs': typeof ServicesSpecialNeedsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/instructors'
    | '/services'
    | '/work-with-us'
    | '/services/private-coaching'
    | '/services/senior-communities'
    | '/services/special-needs'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/instructors'
    | '/work-with-us'
    | '/services/private-coaching'
    | '/services/senior-communities'
    | '/services/special-needs'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/instructors'
    | '/services'
    | '/work-with-us'
    | '/services/private-coaching'
    | '/services/senior-communities'
    | '/services/special-needs'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InstructorsRoute: typeof InstructorsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  WorkWithUsRoute: typeof WorkWithUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/special-needs': {
      id: '/services/special-needs'
      path: '/special-needs'
      fullPath: '/services/special-needs'
      preLoaderRoute: typeof ServicesSpecialNeedsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/senior-communities': {
      id: '/services/senior-communities'
      path: '/senior-communities'
      fullPath: '/services/senior-communities'
      preLoaderRoute: typeof ServicesSeniorCommunitiesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/private-coaching': {
      id: '/services/private-coaching'
      path: '/private-coaching'
      fullPath: '/services/private-coaching'
      preLoaderRoute: typeof ServicesPrivateCoachingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesPrivateCoachingRoute: typeof ServicesPrivateCoachingRoute
  ServicesSeniorCommunitiesRoute: typeof ServicesSeniorCommunitiesRoute
  ServicesSpecialNeedsRoute: typeof ServicesSpecialNeedsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesPrivateCoachingRoute: ServicesPrivateCoachingRoute,
  ServicesSeniorCommunitiesRoute: ServicesSeniorCommunitiesRoute,
  ServicesSpecialNeedsRoute: ServicesSpecialNeedsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InstructorsRoute: InstructorsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  WorkWithUsRoute: WorkWithUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
